package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrycstvvAppointmentsLecturersMatheInf generated by hbm2java
 */
@Entity
@Table(name = "qrycstvv_appointments_lecturers_mathe_inf", catalog = "sakai292")
public class QrycstvvAppointmentsLecturersMatheInf implements
		java.io.Serializable {

	private QrycstvvAppointmentsLecturersMatheInfId id;

	public QrycstvvAppointmentsLecturersMatheInf() {
	}

	public QrycstvvAppointmentsLecturersMatheInf(
			QrycstvvAppointmentsLecturersMatheInfId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "appointmentId", column = @Column(name = "appointment_id", nullable = false)),
			@AttributeOverride(name = "lecturerId", column = @Column(name = "lecturer_id", nullable = false)),
			@AttributeOverride(name = "role", column = @Column(name = "role", length = 510)) })
	public QrycstvvAppointmentsLecturersMatheInfId getId() {
		return this.id;
	}

	public void setId(QrycstvvAppointmentsLecturersMatheInfId id) {
		this.id = id;
	}

}
