package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QrycstvvBuildings generated by hbm2java
 */
@Entity
@Table(name = "qrycstvv_buildings", catalog = "sakai292")
public class QrycstvvBuildings implements java.io.Serializable {

	private int id;
	private String name;
	private String shortName;
	private String street;
	private String plz;
	private String city;
	private String location;
	private Date createdAt;
	private Date updatedAt;

	public QrycstvvBuildings() {
	}

	public QrycstvvBuildings(int id, String shortName, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.shortName = shortName;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public QrycstvvBuildings(int id, String name, String shortName,
			String street, String plz, String city, String location,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.name = name;
		this.shortName = shortName;
		this.street = street;
		this.plz = plz;
		this.city = city;
		this.location = location;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "short_name", nullable = false, length = 20)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "street")
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "plz", length = 20)
	public String getPlz() {
		return this.plz;
	}

	public void setPlz(String plz) {
		this.plz = plz;
	}

	@Column(name = "city", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "location", length = 100)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
