package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QrycstvvCoursesMatheInf generated by hbm2java
 */
@Entity
@Table(name = "qrycstvv_courses_mathe_inf", catalog = "sakai292")
public class QrycstvvCoursesMatheInf implements java.io.Serializable {

	private int id;
	private String statusName;
	private String nr;
	private String name;
	private String nameEn;
	private String semester;
	private String category;
	private String categoryEn;
	private String commentary;
	private String commentaryEn;
	private String reading;
	private String readingEn;
	private String additionalInfo;
	private String additionalInfoEn;
	private String studentInfo;
	private String studentInfoEn;
	private String time;
	private String place;
	private String instructor;
	private Byte cancelled;
	private String provider;
	private String contextInfo;
	private short participants;
	private Date startingDate;
	private Date endingDate;
	private Byte required;
	private Byte limited;
	private String language;
	private String languageEn;
	private String info;
	private Date infoExpiry;
	private Byte publish;
	private int semesterId;
	private String semInfo;
	private BigDecimal hours;
	private String credits;
	private Date createdAt;
	private Date updatedAt;

	public QrycstvvCoursesMatheInf() {
	}

	public QrycstvvCoursesMatheInf(int id, String statusName, String name,
			String nameEn, String semester, String category, String categoryEn,
			String provider, short participants, int semesterId, Date createdAt) {
		this.id = id;
		this.statusName = statusName;
		this.name = name;
		this.nameEn = nameEn;
		this.semester = semester;
		this.category = category;
		this.categoryEn = categoryEn;
		this.provider = provider;
		this.participants = participants;
		this.semesterId = semesterId;
		this.createdAt = createdAt;
	}

	public QrycstvvCoursesMatheInf(int id, String statusName, String nr,
			String name, String nameEn, String semester, String category,
			String categoryEn, String commentary, String commentaryEn,
			String reading, String readingEn, String additionalInfo,
			String additionalInfoEn, String studentInfo, String studentInfoEn,
			String time, String place, String instructor, Byte cancelled,
			String provider, String contextInfo, short participants,
			Date startingDate, Date endingDate, Byte required, Byte limited,
			String language, String languageEn, String info, Date infoExpiry,
			Byte publish, int semesterId, String semInfo, BigDecimal hours,
			String credits, Date createdAt, Date updatedAt) {
		this.id = id;
		this.statusName = statusName;
		this.nr = nr;
		this.name = name;
		this.nameEn = nameEn;
		this.semester = semester;
		this.category = category;
		this.categoryEn = categoryEn;
		this.commentary = commentary;
		this.commentaryEn = commentaryEn;
		this.reading = reading;
		this.readingEn = readingEn;
		this.additionalInfo = additionalInfo;
		this.additionalInfoEn = additionalInfoEn;
		this.studentInfo = studentInfo;
		this.studentInfoEn = studentInfoEn;
		this.time = time;
		this.place = place;
		this.instructor = instructor;
		this.cancelled = cancelled;
		this.provider = provider;
		this.contextInfo = contextInfo;
		this.participants = participants;
		this.startingDate = startingDate;
		this.endingDate = endingDate;
		this.required = required;
		this.limited = limited;
		this.language = language;
		this.languageEn = languageEn;
		this.info = info;
		this.infoExpiry = infoExpiry;
		this.publish = publish;
		this.semesterId = semesterId;
		this.semInfo = semInfo;
		this.hours = hours;
		this.credits = credits;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "StatusName", nullable = false, length = 100)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "nr", length = 100)
	public String getNr() {
		return this.nr;
	}

	public void setNr(String nr) {
		this.nr = nr;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "name_en", nullable = false)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Column(name = "Semester", nullable = false)
	public String getSemester() {
		return this.semester;
	}

	public void setSemester(String semester) {
		this.semester = semester;
	}

	@Column(name = "category", nullable = false, length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "category_en", nullable = false, length = 100)
	public String getCategoryEn() {
		return this.categoryEn;
	}

	public void setCategoryEn(String categoryEn) {
		this.categoryEn = categoryEn;
	}

	@Column(name = "commentary", length = 65535)
	public String getCommentary() {
		return this.commentary;
	}

	public void setCommentary(String commentary) {
		this.commentary = commentary;
	}

	@Column(name = "commentary_en", length = 65535)
	public String getCommentaryEn() {
		return this.commentaryEn;
	}

	public void setCommentaryEn(String commentaryEn) {
		this.commentaryEn = commentaryEn;
	}

	@Column(name = "reading", length = 65535)
	public String getReading() {
		return this.reading;
	}

	public void setReading(String reading) {
		this.reading = reading;
	}

	@Column(name = "reading_en", length = 65535)
	public String getReadingEn() {
		return this.readingEn;
	}

	public void setReadingEn(String readingEn) {
		this.readingEn = readingEn;
	}

	@Column(name = "additional_info", length = 65535)
	public String getAdditionalInfo() {
		return this.additionalInfo;
	}

	public void setAdditionalInfo(String additionalInfo) {
		this.additionalInfo = additionalInfo;
	}

	@Column(name = "additional_info_en", length = 65535)
	public String getAdditionalInfoEn() {
		return this.additionalInfoEn;
	}

	public void setAdditionalInfoEn(String additionalInfoEn) {
		this.additionalInfoEn = additionalInfoEn;
	}

	@Column(name = "student_info", length = 65535)
	public String getStudentInfo() {
		return this.studentInfo;
	}

	public void setStudentInfo(String studentInfo) {
		this.studentInfo = studentInfo;
	}

	@Column(name = "student_info_en", length = 65535)
	public String getStudentInfoEn() {
		return this.studentInfoEn;
	}

	public void setStudentInfoEn(String studentInfoEn) {
		this.studentInfoEn = studentInfoEn;
	}

	@Column(name = "time", length = 65535)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "place", length = 65535)
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "instructor")
	public String getInstructor() {
		return this.instructor;
	}

	public void setInstructor(String instructor) {
		this.instructor = instructor;
	}

	@Column(name = "cancelled")
	public Byte getCancelled() {
		return this.cancelled;
	}

	public void setCancelled(Byte cancelled) {
		this.cancelled = cancelled;
	}

	@Column(name = "provider", nullable = false)
	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	@Column(name = "context_info", length = 65535)
	public String getContextInfo() {
		return this.contextInfo;
	}

	public void setContextInfo(String contextInfo) {
		this.contextInfo = contextInfo;
	}

	@Column(name = "participants", nullable = false)
	public short getParticipants() {
		return this.participants;
	}

	public void setParticipants(short participants) {
		this.participants = participants;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "starting_date", length = 19)
	public Date getStartingDate() {
		return this.startingDate;
	}

	public void setStartingDate(Date startingDate) {
		this.startingDate = startingDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ending_date", length = 19)
	public Date getEndingDate() {
		return this.endingDate;
	}

	public void setEndingDate(Date endingDate) {
		this.endingDate = endingDate;
	}

	@Column(name = "required")
	public Byte getRequired() {
		return this.required;
	}

	public void setRequired(Byte required) {
		this.required = required;
	}

	@Column(name = "limited")
	public Byte getLimited() {
		return this.limited;
	}

	public void setLimited(Byte limited) {
		this.limited = limited;
	}

	@Column(name = "language", length = 50)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "language_en")
	public String getLanguageEn() {
		return this.languageEn;
	}

	public void setLanguageEn(String languageEn) {
		this.languageEn = languageEn;
	}

	@Column(name = "info")
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "info_expiry", length = 19)
	public Date getInfoExpiry() {
		return this.infoExpiry;
	}

	public void setInfoExpiry(Date infoExpiry) {
		this.infoExpiry = infoExpiry;
	}

	@Column(name = "publish")
	public Byte getPublish() {
		return this.publish;
	}

	public void setPublish(Byte publish) {
		this.publish = publish;
	}

	@Column(name = "semester_id", nullable = false)
	public int getSemesterId() {
		return this.semesterId;
	}

	public void setSemesterId(int semesterId) {
		this.semesterId = semesterId;
	}

	@Column(name = "sem_info", length = 65535)
	public String getSemInfo() {
		return this.semInfo;
	}

	public void setSemInfo(String semInfo) {
		this.semInfo = semInfo;
	}

	@Column(name = "hours", precision = 10)
	public BigDecimal getHours() {
		return this.hours;
	}

	public void setHours(BigDecimal hours) {
		this.hours = hours;
	}

	@Column(name = "credits", length = 65535)
	public String getCredits() {
		return this.credits;
	}

	public void setCredits(String credits) {
		this.credits = credits;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
