package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QrycstvvExtendendNodes generated by hbm2java
 */
@Entity
@Table(name = "qrycstvv_extendend_nodes", catalog = "sakai292")
public class QrycstvvExtendendNodes implements java.io.Serializable {

	private int id;
	private int nodeType;
	private String nodeTypeName;
	private String abbreviation;
	private String name;
	private String nameEn;
	private Date createdAt;
	private Date updatedAt;

	public QrycstvvExtendendNodes() {
	}

	public QrycstvvExtendendNodes(int id, int nodeType, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.nodeType = nodeType;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public QrycstvvExtendendNodes(int id, int nodeType, String nodeTypeName,
			String abbreviation, String name, String nameEn, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.nodeType = nodeType;
		this.nodeTypeName = nodeTypeName;
		this.abbreviation = abbreviation;
		this.name = name;
		this.nameEn = nameEn;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "node_type", nullable = false)
	public int getNodeType() {
		return this.nodeType;
	}

	public void setNodeType(int nodeType) {
		this.nodeType = nodeType;
	}

	@Column(name = "node_type_name", length = 100)
	public String getNodeTypeName() {
		return this.nodeTypeName;
	}

	public void setNodeTypeName(String nodeTypeName) {
		this.nodeTypeName = nodeTypeName;
	}

	@Column(name = "abbreviation", length = 510)
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@Column(name = "name", length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "name_en", length = 510)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
