package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QrycstvvAppointments generated by hbm2java
 */
@Entity
@Table(name = "qrycstvv_appointments", catalog = "sakai292")
public class QrycstvvAppointments implements java.io.Serializable {

	private int id;
	private int seriesId;
	private int courseId;
	private Date startingDate;
	private Date endingDate;
	private String name;
	private String commentary;
	private Date createdAt;
	private Date updatedAt;

	public QrycstvvAppointments() {
	}

	public QrycstvvAppointments(int id, int seriesId, int courseId,
			Date startingDate, Date endingDate) {
		this.id = id;
		this.seriesId = seriesId;
		this.courseId = courseId;
		this.startingDate = startingDate;
		this.endingDate = endingDate;
	}

	public QrycstvvAppointments(int id, int seriesId, int courseId,
			Date startingDate, Date endingDate, String name, String commentary,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.seriesId = seriesId;
		this.courseId = courseId;
		this.startingDate = startingDate;
		this.endingDate = endingDate;
		this.name = name;
		this.commentary = commentary;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "series_id", nullable = false)
	public int getSeriesId() {
		return this.seriesId;
	}

	public void setSeriesId(int seriesId) {
		this.seriesId = seriesId;
	}

	@Column(name = "course_id", nullable = false)
	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "starting_date", nullable = false, length = 19)
	public Date getStartingDate() {
		return this.startingDate;
	}

	public void setStartingDate(Date startingDate) {
		this.startingDate = startingDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ending_date", nullable = false, length = 19)
	public Date getEndingDate() {
		return this.endingDate;
	}

	public void setEndingDate(Date endingDate) {
		this.endingDate = endingDate;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "commentary", length = 65535)
	public String getCommentary() {
		return this.commentary;
	}

	public void setCommentary(String commentary) {
		this.commentary = commentary;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
