package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QrycstvvAppointmentsLecturersId generated by hbm2java
 */
@Embeddable
public class QrycstvvAppointmentsLecturersId implements java.io.Serializable {

	private int appointmentId;
	private int lecturerId;
	private String role;

	public QrycstvvAppointmentsLecturersId() {
	}

	public QrycstvvAppointmentsLecturersId(int appointmentId, int lecturerId) {
		this.appointmentId = appointmentId;
		this.lecturerId = lecturerId;
	}

	public QrycstvvAppointmentsLecturersId(int appointmentId, int lecturerId,
			String role) {
		this.appointmentId = appointmentId;
		this.lecturerId = lecturerId;
		this.role = role;
	}

	@Column(name = "appointment_id", nullable = false)
	public int getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(int appointmentId) {
		this.appointmentId = appointmentId;
	}

	@Column(name = "lecturer_id", nullable = false)
	public int getLecturerId() {
		return this.lecturerId;
	}

	public void setLecturerId(int lecturerId) {
		this.lecturerId = lecturerId;
	}

	@Column(name = "role", length = 510)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QrycstvvAppointmentsLecturersId))
			return false;
		QrycstvvAppointmentsLecturersId castOther = (QrycstvvAppointmentsLecturersId) other;

		return (this.getAppointmentId() == castOther.getAppointmentId())
				&& (this.getLecturerId() == castOther.getLecturerId())
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null
						&& castOther.getRole() != null && this.getRole()
						.equals(castOther.getRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAppointmentId();
		result = 37 * result + this.getLecturerId();
		result = 37 * result
				+ (getRole() == null ? 0 : this.getRole().hashCode());
		return result;
	}

}
