package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QrycstvvAppointmentsRoomsMatheInfId generated by hbm2java
 */
@Embeddable
public class QrycstvvAppointmentsRoomsMatheInfId implements
		java.io.Serializable {

	private int appointmentId;
	private int roomId;

	public QrycstvvAppointmentsRoomsMatheInfId() {
	}

	public QrycstvvAppointmentsRoomsMatheInfId(int appointmentId, int roomId) {
		this.appointmentId = appointmentId;
		this.roomId = roomId;
	}

	@Column(name = "appointment_id", nullable = false)
	public int getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(int appointmentId) {
		this.appointmentId = appointmentId;
	}

	@Column(name = "room_id", nullable = false)
	public int getRoomId() {
		return this.roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QrycstvvAppointmentsRoomsMatheInfId))
			return false;
		QrycstvvAppointmentsRoomsMatheInfId castOther = (QrycstvvAppointmentsRoomsMatheInfId) other;

		return (this.getAppointmentId() == castOther.getAppointmentId())
				&& (this.getRoomId() == castOther.getRoomId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAppointmentId();
		result = 37 * result + this.getRoomId();
		return result;
	}

}
