package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrycstvvExtendedNodesProgramComponents generated by hbm2java
 */
@Entity
@Table(name = "qrycstvv_extended_nodes_program_components", catalog = "sakai292")
public class QrycstvvExtendedNodesProgramComponents implements
		java.io.Serializable {

	private QrycstvvExtendedNodesProgramComponentsId id;

	public QrycstvvExtendedNodesProgramComponents() {
	}

	public QrycstvvExtendedNodesProgramComponents(
			QrycstvvExtendedNodesProgramComponentsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "programComponentId", column = @Column(name = "program_component_id", nullable = false)),
			@AttributeOverride(name = "extendedNodeId", column = @Column(name = "extended_node_id", nullable = false)),
			@AttributeOverride(name = "sortfield", column = @Column(name = "sortfield", nullable = false)) })
	public QrycstvvExtendedNodesProgramComponentsId getId() {
		return this.id;
	}

	public void setId(QrycstvvExtendedNodesProgramComponentsId id) {
		this.id = id;
	}

}
