package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QrycstvvSemesters generated by hbm2java
 */
@Entity
@Table(name = "qrycstvv_semesters", catalog = "sakai292")
public class QrycstvvSemesters implements java.io.Serializable {

	private int id;
	private String shortName;
	private String name;
	private Byte publish;
	private Byte hidden;
	private String textfield;
	private String textfieldEn;
	private Date beginDate;
	private Date createdAt;
	private Date updatedAt;

	public QrycstvvSemesters() {
	}

	public QrycstvvSemesters(int id, String name, Date createdAt, Date updatedAt) {
		this.id = id;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public QrycstvvSemesters(int id, String shortName, String name,
			Byte publish, Byte hidden, String textfield, String textfieldEn,
			Date beginDate, Date createdAt, Date updatedAt) {
		this.id = id;
		this.shortName = shortName;
		this.name = name;
		this.publish = publish;
		this.hidden = hidden;
		this.textfield = textfield;
		this.textfieldEn = textfieldEn;
		this.beginDate = beginDate;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "short_name", length = 50)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "publish")
	public Byte getPublish() {
		return this.publish;
	}

	public void setPublish(Byte publish) {
		this.publish = publish;
	}

	@Column(name = "hidden")
	public Byte getHidden() {
		return this.hidden;
	}

	public void setHidden(Byte hidden) {
		this.hidden = hidden;
	}

	@Column(name = "textfield", length = 65535)
	public String getTextfield() {
		return this.textfield;
	}

	public void setTextfield(String textfield) {
		this.textfield = textfield;
	}

	@Column(name = "textfield_en", length = 65535)
	public String getTextfieldEn() {
		return this.textfieldEn;
	}

	public void setTextfieldEn(String textfieldEn) {
		this.textfieldEn = textfieldEn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "begin_date", length = 19)
	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
