package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QrycstvvTextblocks generated by hbm2java
 */
@Entity
@Table(name = "qrycstvv_textblocks", catalog = "sakai292")
public class QrycstvvTextblocks implements java.io.Serializable {

	private int id;
	private String facultyId;
	private Integer subjectId;
	private Integer degreeId;
	private Integer programComponentId;
	private Integer extendedNodeId;
	private String textField;
	private String textFieldEn;
	private int semesterId;
	private Date createdAt;
	private Date updatedAt;

	public QrycstvvTextblocks() {
	}

	public QrycstvvTextblocks(int id, int semesterId, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.semesterId = semesterId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public QrycstvvTextblocks(int id, String facultyId, Integer subjectId,
			Integer degreeId, Integer programComponentId,
			Integer extendedNodeId, String textField, String textFieldEn,
			int semesterId, Date createdAt, Date updatedAt) {
		this.id = id;
		this.facultyId = facultyId;
		this.subjectId = subjectId;
		this.degreeId = degreeId;
		this.programComponentId = programComponentId;
		this.extendedNodeId = extendedNodeId;
		this.textField = textField;
		this.textFieldEn = textFieldEn;
		this.semesterId = semesterId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "faculty_id", length = 30)
	public String getFacultyId() {
		return this.facultyId;
	}

	public void setFacultyId(String facultyId) {
		this.facultyId = facultyId;
	}

	@Column(name = "subject_id")
	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "degree_id")
	public Integer getDegreeId() {
		return this.degreeId;
	}

	public void setDegreeId(Integer degreeId) {
		this.degreeId = degreeId;
	}

	@Column(name = "program_component_id")
	public Integer getProgramComponentId() {
		return this.programComponentId;
	}

	public void setProgramComponentId(Integer programComponentId) {
		this.programComponentId = programComponentId;
	}

	@Column(name = "extended_node_id")
	public Integer getExtendedNodeId() {
		return this.extendedNodeId;
	}

	public void setExtendedNodeId(Integer extendedNodeId) {
		this.extendedNodeId = extendedNodeId;
	}

	@Column(name = "text_field", length = 65535)
	public String getTextField() {
		return this.textField;
	}

	public void setTextField(String textField) {
		this.textField = textField;
	}

	@Column(name = "text_field_en", length = 65535)
	public String getTextFieldEn() {
		return this.textFieldEn;
	}

	public void setTextFieldEn(String textFieldEn) {
		this.textFieldEn = textFieldEn;
	}

	@Column(name = "semester_id", nullable = false)
	public int getSemesterId() {
		return this.semesterId;
	}

	public void setSemesterId(int semesterId) {
		this.semesterId = semesterId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
