package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QrycstvvCoursesExtendedNodesId generated by hbm2java
 */
@Embeddable
public class QrycstvvCoursesExtendedNodesId implements java.io.Serializable {

	private int extendedNodeId;
	private Integer courseId;
	private String submodulAbbr;
	private Integer positionNumber;

	public QrycstvvCoursesExtendedNodesId() {
	}

	public QrycstvvCoursesExtendedNodesId(int extendedNodeId,
			String submodulAbbr) {
		this.extendedNodeId = extendedNodeId;
		this.submodulAbbr = submodulAbbr;
	}

	public QrycstvvCoursesExtendedNodesId(int extendedNodeId, Integer courseId,
			String submodulAbbr, Integer positionNumber) {
		this.extendedNodeId = extendedNodeId;
		this.courseId = courseId;
		this.submodulAbbr = submodulAbbr;
		this.positionNumber = positionNumber;
	}

	@Column(name = "extended_node_id", nullable = false)
	public int getExtendedNodeId() {
		return this.extendedNodeId;
	}

	public void setExtendedNodeId(int extendedNodeId) {
		this.extendedNodeId = extendedNodeId;
	}

	@Column(name = "course_id")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "submodul_abbr", nullable = false, length = 100)
	public String getSubmodulAbbr() {
		return this.submodulAbbr;
	}

	public void setSubmodulAbbr(String submodulAbbr) {
		this.submodulAbbr = submodulAbbr;
	}

	@Column(name = "position_number")
	public Integer getPositionNumber() {
		return this.positionNumber;
	}

	public void setPositionNumber(Integer positionNumber) {
		this.positionNumber = positionNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QrycstvvCoursesExtendedNodesId))
			return false;
		QrycstvvCoursesExtendedNodesId castOther = (QrycstvvCoursesExtendedNodesId) other;

		return (this.getExtendedNodeId() == castOther.getExtendedNodeId())
				&& ((this.getCourseId() == castOther.getCourseId()) || (this
						.getCourseId() != null
						&& castOther.getCourseId() != null && this
						.getCourseId().equals(castOther.getCourseId())))
				&& ((this.getSubmodulAbbr() == castOther.getSubmodulAbbr()) || (this
						.getSubmodulAbbr() != null
						&& castOther.getSubmodulAbbr() != null && this
						.getSubmodulAbbr().equals(castOther.getSubmodulAbbr())))
				&& ((this.getPositionNumber() == castOther.getPositionNumber()) || (this
						.getPositionNumber() != null
						&& castOther.getPositionNumber() != null && this
						.getPositionNumber().equals(
								castOther.getPositionNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getExtendedNodeId();
		result = 37 * result
				+ (getCourseId() == null ? 0 : this.getCourseId().hashCode());
		result = 37
				* result
				+ (getSubmodulAbbr() == null ? 0 : this.getSubmodulAbbr()
						.hashCode());
		result = 37
				* result
				+ (getPositionNumber() == null ? 0 : this.getPositionNumber()
						.hashCode());
		return result;
	}

}
