package de.juffel.kvv.model;

// Generated Jun 15, 2014 8:11:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QrycstvvExtendedNodesProgramComponentsId generated by hbm2java
 */
@Embeddable
public class QrycstvvExtendedNodesProgramComponentsId implements
		java.io.Serializable {

	private int programComponentId;
	private int extendedNodeId;
	private int sortfield;

	public QrycstvvExtendedNodesProgramComponentsId() {
	}

	public QrycstvvExtendedNodesProgramComponentsId(int programComponentId,
			int extendedNodeId, int sortfield) {
		this.programComponentId = programComponentId;
		this.extendedNodeId = extendedNodeId;
		this.sortfield = sortfield;
	}

	@Column(name = "program_component_id", nullable = false)
	public int getProgramComponentId() {
		return this.programComponentId;
	}

	public void setProgramComponentId(int programComponentId) {
		this.programComponentId = programComponentId;
	}

	@Column(name = "extended_node_id", nullable = false)
	public int getExtendedNodeId() {
		return this.extendedNodeId;
	}

	public void setExtendedNodeId(int extendedNodeId) {
		this.extendedNodeId = extendedNodeId;
	}

	@Column(name = "sortfield", nullable = false)
	public int getSortfield() {
		return this.sortfield;
	}

	public void setSortfield(int sortfield) {
		this.sortfield = sortfield;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QrycstvvExtendedNodesProgramComponentsId))
			return false;
		QrycstvvExtendedNodesProgramComponentsId castOther = (QrycstvvExtendedNodesProgramComponentsId) other;

		return (this.getProgramComponentId() == castOther
				.getProgramComponentId())
				&& (this.getExtendedNodeId() == castOther.getExtendedNodeId())
				&& (this.getSortfield() == castOther.getSortfield());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProgramComponentId();
		result = 37 * result + this.getExtendedNodeId();
		result = 37 * result + this.getSortfield();
		return result;
	}

}
